### ISSUE TITLE
play() has a massive delay on iPhone 4

### ISSUE THREAD

**Issue by timaschew** [kevincennis/TinyMusic#10]
I patched the play function to proof if I can track each note via a callback. It works on chrome, firefox, and safari and chrome mobile, but on a safari on an iPhone 4 it is not in sync, it has a delay / offset of 7 seconds for 11 notes.

Here is a fiddle:
http://jsbin.com/xedarijowo/edit?html,js,output //link was updated

and here is a video how it looks and feels on the iPhone: https://drive.google.com/file/d/0BxBhpxgEmPGPM3VVcTYxOXRwWEE/view?usp=sharing

If I open the demo fiddle of you, there is only a short delay of 3 seconds, but the melody and notes are much more complex. But If I stop it the first time and play it again, it starts on the next play click almost immediately.

**Comment by kevincennis** [comment]
Hmm. Which version of iOS are you running?

If I can get my hands on an iPhone 4 I'll take a look. 

Am I understanding you correctly that the `onended` callbacks are firing at the right time, but the actual audio is delayed? If that's the case, it sounds like it might be a lower-level bug with Safari.

**Comment by timaschew** [comment]
sorry, the fiddle link was wrong, I updated it.
iOS 7

> Am I understanding you correctly that the onended callbacks are firing at the right time, but the actual audio is delayed?

exactly

I will try it on a newer iPhone of my coworker today.

**Comment by kevincennis** [comment]
Ah, okay. I see what you're doing now.

So, you're not actually using `onended` – you're just setting a timeout, which means you don't actually have any true guarantee that it'll line up with the audio (although it should normally be very close).

Anyway, that fiddle works fine on my iPhone 6 with iOS 8.

I'll see if anyone at the office has an older iPhone with iOS 7 – but if not, I might not really be able to offer much help with this bug for a while.

**Comment by kevincennis** [comment]
Actually, another thing I noticed:

You're doing *everything* on that click event, including setting up an `AudioContext`, creating the `Sequence`, instantiating all of the `Note` instances from strings, creating the gain and EQ nodes, etc.

That stuff shouldn't take *too* long, but it's a decent amount of up-front work.

You might want to try setting all of those things up beforehand, and just have the button call `Sequence.play()` instead.

**Comment by timaschew** [comment]
> So, you're not actually using onended

How I can use a callback for each note for `onended`?

> You might want to try setting all of those things up beforehand, and just have the button call Sequence.play() instead.

I tried this, but then it's there is a delay the other way, the sound is playing fine, but the callbacks are fired with a delay which is equal to the timerange between opening the page (and setup the AudioContext) and clicking the button (playing).

**Comment by kevincennis** [comment]
Yeah, sorry. You're right about the callbacks. It's too early and the coffee hasn't kicked in yet.

Can you give this a shot? http://jsbin.com/quqetumuju/edit?html,js,output

I changed the play function a bit to fix some timing issues in your version, and added a random delay to the `sequence.play()` call just to sort of prove out the changes I made.

**Comment by kevincennis** [comment]
Also: I'm going to close out this issue, since TinyMusic doesn't support per-note callbacks. You're more than welcome to add them on your own, of course.

And I'm still happy to help if that latest fiddle doesn't solve your problem. Let me know how that turns out.

**Comment by timaschew** [comment]
> Can you give this a shot? http://jsbin.com/quqetumuju/edit?html,js,output

looks god, I will test it later on the iPhone 4

> And I'm still happy to help if that latest fiddle doesn't solve your problem. Let me know how that turns out.

Thank you very much for the fast feedback :)

> You're more than welcome to add them on your own, of course.

And make a pull request? or what you mean?

**Comment by kevincennis** [comment]
I meant by either forking TinyMusic or by overriding `Sequence.prototype.play` in your own project.
