### ISSUE TITLE
Timing Events

### ISSUE THREAD

**Issue by cawoodm** [kevincennis/TinyMusic#14]
In your demo you have the harmony coming in after 16 beats.
In order to make interesting tunes it would be neat to be able to randomly start and stop a sequence.
So after 16 bars stop the base for 4 bars.
The challenge I see is timing: how would one do this at the correct time i.e. at the end of a defined bar?
I imagine you would need to publish an event onBarEnd(n) which could be used to determine if bar number n is finished and thus change a sequence.

**Comment by kevincennis** [comment]
It would definitely be possible to extend TinyMusic to support something like that – but it's a bit outside the scope of what I want to support. The library was really intended for playing back simple pre-defined melodies.

But you're definitely welcome to fork the repo and add that stuff yourself. If you ended up doing that, let me know. I'd love to see it.

**Comment by cawoodm** [comment]
OK, it seems to be as easy as binding to Sequence.osc.onend():
```
	seq2.osc.onended = function() {
		seq2.play( G.music.ac.currentTime + ( 60 / G.music.tempo ) * 16 );
	}
```
So, after playing seq2 once it will stop and the wait 16 bars before playing it again.
