### ISSUE TITLE
Getting an InvalidStateError in Safari and iOS.

### ISSUE THREAD

**Issue by robertpage** [kevincennis/TinyMusic#6]
I added this library to a small game I made recently and it's been great. Although, it was brought to my attention that the music wasn't looping on Safari and iOS. The demo(http://jsbin.com/pavelunima/1/edit?js,output) is throwing the same error:
DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.
Thanks for your time and thanks for awesome library.

**Comment by kevincennis** [comment]
Pretty sure I know what's causing this...

I believe `stop()` is being called multiple times on an `OscillatorNode`. From what I remember, this should be (or used to be?) allowed – but maybe isn't anymore in Safari.

I should be able to fix this pretty easily later tonight :pray:

**Comment by robertpage** [comment]
Wow, thanks for the quick response!

**Comment by kevincennis** [comment]
Should be all set now. Verified in Safari on my Macbook, and everything works. Package has been updated on npm after a bump to `0.0.3`.

Thanks for reporting this, and sorry it took a little bit longer to fix than I initially quoted. I actually started looking into it last night, but took a break for dinner and then immediately passed out like a very, very old man.

**Comment by robertpage** [comment]
Wow, thanks! I super appreciate this. I really like TinyMusic. I've never made music before so I had a lot of fun figuring it out. The game I made was actually part of an interview where I was tasked with making Wack-a-Mole in the browser. Here's the game:
http://robertpage.github.io/moles/
Also, I appreciate that you had a Ratatat song as part of your demo.
